import{runtimeEnv}from"./store";
export type ReservedProduct={id:number;name:string;price_pen:number;quantity:number};
export async function releaseExpiredReservations(){const db=runtimeEnv().DB,now=new Date().toISOString();await db.batch([db.prepare("UPDATE inventory_reservations SET status='released',updated_at=? WHERE status='active' AND expires_at<=?").bind(now,now),db.prepare("UPDATE orders SET status='expired',payment_status='expired' WHERE status='awaiting_payment' AND expires_at<=? AND EXISTS(SELECT 1 FROM inventory_reservations WHERE order_id=orders.id AND status='released')").bind(now)])}
export async function reserveOrder(input:{orderId:string;email:string;idempotencyKey:string;checkoutFingerprint:string;products:ReservedProduct[];total:number;expiresAt:string}){const db=runtimeEnv().DB,now=new Date().toISOString(),reservationId=crypto.randomUUID();await db.batch([db.prepare("INSERT INTO orders(id,customer_email,currency,total,status,payment_status,idempotency_key,checkout_fingerprint,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(input.orderId,input.email,"PEN",input.total,"awaiting_payment","pending",input.idempotencyKey,input.checkoutFingerprint,input.expiresAt,now),db.prepare("INSERT INTO inventory_reservations(id,order_id,status,expires_at,created_at,updated_at) VALUES(?,?,'active',?,?,?)").bind(reservationId,input.orderId,input.expiresAt,now,now),...input.products.map(p=>db.prepare("INSERT INTO order_items(order_id,product_id,name,unit_price,quantity) VALUES(?,?,?,?,?)").bind(input.orderId,p.id,p.name,p.price_pen,p.quantity)),...input.products.map(p=>db.prepare("INSERT INTO reservation_items(reservation_id,product_id,quantity) VALUES(?,?,?)").bind(reservationId,p.id,p.quantity))])}
export async function releaseOrder(orderId:string,status="failed"){const db=runtimeEnv().DB,now=new Date().toISOString();await db.batch([db.prepare("UPDATE inventory_reservations SET status='released',updated_at=? WHERE order_id=? AND status='active'").bind(now,orderId),db.prepare("UPDATE orders SET status=? WHERE id=? AND status NOT IN ('paid','payment_review')").bind(status,orderId)])}
function event(db:D1Database,input:{orderId:string;paymentId:string;status:string;eventKey:string},now:string){return db.prepare("INSERT OR IGNORE INTO payment_events(provider,event_key,payment_id,order_id,status,created_at) VALUES('mercadopago',?,?,?,?,?)").bind(input.eventKey,input.paymentId,input.orderId,input.status,now)}
export async function recordPayment(input:{orderId:string;paymentId:string;status:string;eventKey:string}){const db=runtimeEnv().DB,now=new Date().toISOString();
 if(input.status==="approved"){await db.batch([event(db,input,now),db.prepare("UPDATE inventory_reservations SET status='consumed',updated_at=? WHERE order_id=? AND status='active'").bind(now,input.orderId),db.prepare("UPDATE orders SET status='paid',payment_status='approved',payment_id=? WHERE id=? AND (payment_id IS NULL OR payment_id=?) AND EXISTS(SELECT 1 FROM inventory_reservations WHERE order_id=? AND status='consumed')").bind(input.paymentId,input.orderId,input.paymentId,input.orderId),db.prepare("UPDATE orders SET status='payment_review',payment_status='approved' WHERE id=? AND payment_id IS NOT NULL AND payment_id!=?").bind(input.orderId,input.paymentId),db.prepare("UPDATE orders SET status='payment_review',payment_status='approved',payment_id=COALESCE(payment_id,?) WHERE id=? AND EXISTS(SELECT 1 FROM inventory_reservations WHERE order_id=? AND status='released')").bind(input.paymentId,input.orderId,input.orderId)]);return}
 if(["rejected","cancelled","expired"].includes(input.status)){await db.batch([event(db,input,now),db.prepare("UPDATE inventory_reservations SET status='released',updated_at=? WHERE order_id=? AND status='active'").bind(now,input.orderId),db.prepare("UPDATE orders SET status='payment_failed',payment_status=?,payment_id=COALESCE(payment_id,?) WHERE id=? AND status NOT IN ('paid','payment_review')").bind(input.status,input.paymentId,input.orderId),db.prepare("UPDATE orders SET status='payment_review',payment_status=? WHERE id=? AND EXISTS(SELECT 1 FROM inventory_reservations WHERE order_id=? AND status='consumed')").bind(input.status,input.orderId,input.orderId)]);return}
 if(["refunded","charged_back"].includes(input.status)){await db.batch([event(db,input,now),db.prepare("UPDATE orders SET status='payment_review',payment_status=?,payment_id=COALESCE(payment_id,?) WHERE id=?").bind(input.status,input.paymentId,input.orderId)]);return}
 await db.batch([event(db,input,now),db.prepare("UPDATE orders SET payment_status=?,payment_id=COALESCE(payment_id,?) WHERE id=? AND status='awaiting_payment'").bind(input.status,input.paymentId,input.orderId),db.prepare("UPDATE orders SET status='payment_review' WHERE id=? AND payment_id IS NOT NULL AND payment_id!=?").bind(input.orderId,input.paymentId)])}
