import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {DatabaseSync} from "node:sqlite";
import test from "node:test";
import {approvedPaymentStatements} from "../app/lib/payment-state.mjs";
import {mercadoPagoManifest,mercadoPagoSignature,validateMercadoPagoSignature} from "../app/lib/mercadopago-signature.mjs";
import {proxySignature,validateProxySignature} from "../app/lib/proxy-signature.mjs";

const migration0=readFileSync(new URL("../drizzle/0000_yellow_stardust.sql",import.meta.url),"utf8");
const migration1=readFileSync(new URL("../drizzle/0001_secure_auth_inventory.sql",import.meta.url),"utf8");
function baseDatabase(){const db=new DatabaseSync(":memory:");db.exec("PRAGMA foreign_keys=ON");db.exec(migration0);return db}
function database(){const db=baseDatabase();db.exec(migration1);return db}
function seedProducts(db){db.exec("INSERT INTO products(id,name,slug,category,description,emoji,price_pen,stock,active) VALUES(1,'A','a','c','d','x',100,5,1),(2,'B','b','c','d','x',100,1,1)")}
function order(db,id,{quantity=2,expiresAt="2026-08-25T00:00:00.000Z"}={}){db.prepare("INSERT INTO orders(id,customer_email,currency,total,status,payment_status,idempotency_key,checkout_fingerprint,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run(id,"a@example.com","PEN",quantity*100,"awaiting_payment","pending",id,"fingerprint",expiresAt,"2026-08-24T00:00:00.000Z");db.prepare("INSERT INTO inventory_reservations(id,order_id,status,expires_at,created_at,updated_at) VALUES(?,?,'active',?,?,?)").run("R-"+id,id,expiresAt,"2026-08-24T00:00:00.000Z","2026-08-24T00:00:00.000Z");db.prepare("INSERT INTO reservation_items(reservation_id,product_id,quantity) VALUES(?,?,?)").run("R-"+id,1,quantity)}
function applyApproved(db,{orderId,paymentId="PAY-1",eventKey=paymentId+":approved",approvedAt,now="2026-08-25T00:00:01.000Z"}){const plan=approvedPaymentStatements({orderId,paymentId,eventKey,approvedAt,now});db.exec("BEGIN");try{for(const{sql,values}of plan)db.prepare(sql).run(...values);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}}
function expire(db,now="2026-08-25T00:00:00.000Z"){db.prepare("UPDATE inventory_reservations SET status='released',updated_at=? WHERE status='active' AND expires_at<=?").run(now,now);db.prepare("UPDATE orders SET status='expired',payment_status='expired' WHERE status='awaiting_payment' AND expires_at<=? AND EXISTS(SELECT 1 FROM inventory_reservations WHERE order_id=orders.id AND status='released')").run(now)}
function state(db,id){return{...db.prepare("SELECT o.status,o.payment_status,o.payment_id,r.status AS reservation_status,p.stock,p.reserved_stock FROM orders o JOIN inventory_reservations r ON r.order_id=o.id JOIN products p ON p.id=1 WHERE o.id=?").get(id)}}

test("migration 0001 applies to a new and an existing populated database",()=>{const fresh=database();assert.equal(fresh.prepare("SELECT COUNT(*) count FROM sqlite_master WHERE type='trigger'").get().count,4);fresh.close();const existing=baseDatabase();existing.exec("INSERT INTO products(id,name,slug,category,description,emoji,price_pen,stock,active) VALUES(1,'Legacy','legacy','c','d','x',100,5,1)");existing.exec("INSERT INTO orders(id,customer_email,currency,total,status,payment_id,preference_id,created_at) VALUES('OLD','old@example.com','PEN',100,'pending','P-OLD','PREF','2026-01-01T00:00:00Z')");existing.exec(migration1);assert.deepEqual({...existing.prepare("SELECT payment_id,payment_status FROM orders WHERE id='OLD'").get()},{payment_id:"P-OLD",payment_status:"pending"});existing.close()});
test("migration preflight stops before changes when payment ids are ambiguous",()=>{const db=baseDatabase();db.exec("INSERT INTO orders(id,customer_email,currency,total,status,payment_id,created_at) VALUES('A','a@example.com','PEN',100,'paid','DUP','now'),('B','b@example.com','PEN',100,'paid','DUP','now')");assert.throws(()=>db.exec(migration1),/bad JSON path/i);assert.equal(db.prepare("SELECT COUNT(*) count FROM pragma_table_info('products') WHERE name='reserved_stock'").get().count,0);assert.equal(db.prepare("SELECT COUNT(*) count FROM orders WHERE payment_id='DUP'").get().count,2);db.close()});
test("reservation batch rolls back completely when one line lacks stock",()=>{const db=database();seedProducts(db);assert.throws(()=>{db.exec("BEGIN");try{order(db,"O1");db.prepare("INSERT INTO reservation_items(reservation_id,product_id,quantity) VALUES(?,?,?)").run("R-O1",2,2);db.exec("COMMIT")}catch(error){db.exec("ROLLBACK");throw error}},/insufficient_stock/);assert.equal(db.prepare("SELECT reserved_stock FROM products WHERE id=1").get().reserved_stock,0);assert.equal(db.prepare("SELECT COUNT(*) count FROM orders").get().count,0);db.close()});
test("approved payment strictly before expiration consumes stock once",()=>{const db=database();seedProducts(db);order(db,"BEFORE",{quantity:3});applyApproved(db,{orderId:"BEFORE",approvedAt:"2026-08-24T23:59:59.999Z"});assert.deepEqual(state(db,"BEFORE"),{status:"paid",payment_status:"approved",payment_id:"PAY-1",reservation_status:"consumed",stock:2,reserved_stock:0});db.close()});
test("approval exactly at expiration is sent to payment review",()=>{const db=database();seedProducts(db);order(db,"EXACT");applyApproved(db,{orderId:"EXACT",approvedAt:"2026-08-25T00:00:00.000Z"});assert.deepEqual(state(db,"EXACT"),{status:"payment_review",payment_status:"approved",payment_id:"PAY-1",reservation_status:"released",stock:5,reserved_stock:0});db.close()});
test("approval after expiration is reviewed even before cron runs",()=>{const db=database();seedProducts(db);order(db,"LATE");applyApproved(db,{orderId:"LATE",approvedAt:"2026-08-25T00:00:00.001Z"});assert.deepEqual(state(db,"LATE"),{status:"payment_review",payment_status:"approved",payment_id:"PAY-1",reservation_status:"released",stock:5,reserved_stock:0});db.close()});
test("missing provider approval time fails closed",()=>{const db=database();seedProducts(db);order(db,"NO-TIME");applyApproved(db,{orderId:"NO-TIME",approvedAt:null});assert.deepEqual(state(db,"NO-TIME"),{status:"payment_review",payment_status:"approved",payment_id:"PAY-1",reservation_status:"active",stock:5,reserved_stock:2});db.close()});
test("duplicate webhook is idempotent",()=>{const db=database();seedProducts(db);order(db,"DUP",{quantity:3});const input={orderId:"DUP",paymentId:"PAY-DUP",eventKey:"PAY-DUP:approved",approvedAt:"2026-08-24T23:00:00.000Z"};applyApproved(db,input);applyApproved(db,input);assert.equal(db.prepare("SELECT COUNT(*) count FROM payment_events").get().count,1);assert.deepEqual(state(db,"DUP"),{status:"paid",payment_status:"approved",payment_id:"PAY-DUP",reservation_status:"consumed",stock:2,reserved_stock:0});db.close()});
test("cron before or after webhook preserves a safe terminal state",()=>{const before=database();seedProducts(before);order(before,"CRON-FIRST");expire(before,"2026-08-25T00:00:01.000Z");applyApproved(before,{orderId:"CRON-FIRST",approvedAt:"2026-08-24T23:59:59.000Z"});assert.equal(state(before,"CRON-FIRST").status,"payment_review");assert.equal(state(before,"CRON-FIRST").stock,5);before.close();const after=database();seedProducts(after);order(after,"WEBHOOK-FIRST");applyApproved(after,{orderId:"WEBHOOK-FIRST",approvedAt:"2026-08-24T23:59:59.000Z"});expire(after,"2026-08-25T00:00:01.000Z");assert.equal(state(after,"WEBHOOK-FIRST").status,"paid");assert.equal(state(after,"WEBHOOK-FIRST").stock,3);after.close()});
test("two concurrent deliveries for one payment have one inventory effect",async()=>{const db=database();seedProducts(db);order(db,"CONCURRENT",{quantity:3});const input={orderId:"CONCURRENT",paymentId:"PAY-C",eventKey:"PAY-C:approved",approvedAt:"2026-08-24T23:00:00.000Z"};await Promise.all([Promise.resolve().then(()=>applyApproved(db,input)),Promise.resolve().then(()=>applyApproved(db,input))]);assert.equal(db.prepare("SELECT COUNT(*) count FROM payment_events").get().count,1);assert.deepEqual(state(db,"CONCURRENT"),{status:"paid",payment_status:"approved",payment_id:"PAY-C",reservation_status:"consumed",stock:2,reserved_stock:0});db.close()});
test("Mercado Pago signature accepts millisecond timestamps and rejects tampering",async()=>{const id="ABC123",requestId="request-1",ts="1742505638683",secret="test-secret",value=await mercadoPagoSignature(id,requestId,ts,secret);assert.equal(mercadoPagoManifest(id,requestId,ts),"id:abc123;request-id:request-1;ts:1742505638683;");assert.equal(await validateMercadoPagoSignature({xSignature:`ts=${ts},v1=${value}`,xRequestId:requestId,dataId:id,secret}),true);assert.equal(await validateMercadoPagoSignature({xSignature:`ts=${ts},v1=${value}`,xRequestId:requestId,dataId:"different",secret}),false)});
test("trusted proxy requires a strong, fresh, request-bound HMAC",async()=>{const email="admin@example.com",timestamp="1787599000000",method="GET",path="/api/admin/products?view=all",secret="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",signature=await proxySignature(email,timestamp,method,path,secret),input={email,timestamp,method,path,signature,secret,now:Number(timestamp)};assert.equal(await validateProxySignature(input),true);assert.equal(await validateProxySignature({...input,path:"/api/orders"}),false);assert.equal(await validateProxySignature({...input,now:Number(timestamp)+60001}),false);assert.equal(await validateProxySignature({...input,secret:"weak"}),false)});

