import { integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";
export const products=sqliteTable("products",{id:integer("id").primaryKey({autoIncrement:true}),name:text("name").notNull(),slug:text("slug").notNull().unique(),category:text("category").notNull(),description:text("description").notNull(),emoji:text("emoji").notNull(),pricePen:integer("price_pen").notNull(),stock:integer("stock").notNull().default(0),reservedStock:integer("reserved_stock").notNull().default(0),active:integer("active",{mode:"boolean"}).notNull().default(true)});
export const users=sqliteTable("users",{id:text("id").primaryKey(),email:text("email").notNull().unique(),passwordHash:text("password_hash"),role:text("role").notNull().default("customer"),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const sessions=sqliteTable("sessions",{id:text("id").primaryKey(),userId:text("user_id").notNull().references(()=>users.id,{onDelete:"cascade"}),tokenHash:text("token_hash").notNull().unique(),expiresAt:text("expires_at").notNull(),createdAt:text("created_at").notNull(),lastSeenAt:text("last_seen_at").notNull()});
export const orders=sqliteTable("orders",{id:text("id").primaryKey(),customerEmail:text("customer_email").notNull(),currency:text("currency").notNull().default("PEN"),total:integer("total").notNull(),status:text("status").notNull().default("pending"),paymentId:text("payment_id"),preferenceId:text("preference_id"),idempotencyKey:text("idempotency_key"),checkoutUrl:text("checkout_url"),expiresAt:text("expires_at"),createdAt:text("created_at").notNull()},t=>[uniqueIndex("orders_customer_idempotency_unique").on(t.customerEmail,t.idempotencyKey)]);
export const orderItems=sqliteTable("order_items",{id:integer("id").primaryKey({autoIncrement:true}),orderId:text("order_id").notNull().references(()=>orders.id,{onDelete:"cascade"}),productId:integer("product_id").notNull().references(()=>products.id),name:text("name").notNull(),unitPrice:integer("unit_price").notNull(),quantity:integer("quantity").notNull()});
export const inventoryReservations=sqliteTable("inventory_reservations",{id:text("id").primaryKey(),orderId:text("order_id").notNull().unique().references(()=>orders.id,{onDelete:"cascade"}),status:text("status").notNull(),expiresAt:text("expires_at").notNull(),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()});
export const reservationItems=sqliteTable("reservation_items",{id:integer("id").primaryKey({autoIncrement:true}),reservationId:text("reservation_id").notNull().references(()=>inventoryReservations.id,{onDelete:"cascade"}),productId:integer("product_id").notNull().references(()=>products.id),quantity:integer("quantity").notNull()});
export const paymentEvents=sqliteTable("payment_events",{id:integer("id").primaryKey({autoIncrement:true}),provider:text("provider").notNull(),eventKey:text("event_key").notNull(),paymentId:text("payment_id").notNull(),orderId:text("order_id").notNull().references(()=>orders.id),status:text("status").notNull(),createdAt:text("created_at").notNull()},t=>[uniqueIndex("payment_events_provider_event_unique").on(t.provider,t.eventKey)]);
